# Generated by Django 4.0.1 on 2022-01-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('introtext', models.TextField(blank=True, null=True)),
                ('fulltext', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('publish_up', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('publish_down', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('metakey', models.TextField(blank=True, null=True)),
                ('metadesc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
