# Generated by Django 4.0.1 on 2022-01-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_down',
            field=models.DateTimeField(db_index=True, default='0000-00-00 00:00'),
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_up',
            field=models.DateTimeField(db_index=True, default='0000-00-00 00:00'),
        ),
    ]
