# Generated by Django 4.0.1 on 2022-01-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_content_images_alter_content_publish_down_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publish_down',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_up',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
