# Generated by Django 4.0.1 on 2022-01-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_content_publish_down_alter_content_publish_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='content',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='content',
            name='fulltext',
            field=models.TextField(blank=True, null=True, verbose_name='Полный текст статьи'),
        ),
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.TextField(default='{}', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='content',
            name='introtext',
            field=models.TextField(blank=True, null=True, verbose_name='Вступительный текст статьи'),
        ),
        migrations.AlterField(
            model_name='content',
            name='metadesc',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='content',
            name='metakey',
            field=models.TextField(blank=True, null=True, verbose_name='Meta keywords'),
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_down',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Публикация до (если оставить поле пустым, то бессрочно)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_up',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Публикация с (если оставить поле пустым, то с даты создания)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категория'),
        ),
    ]
