# Generated by Django 4.0.1 on 2022-01-20 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_content_options_alter_content_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='images',
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_down',
            field=models.DateTimeField(blank=True, db_index=True, help_text='<span style="color:red;">если оставить поле пустым, то бессрочно</span>', null=True, verbose_name='Публикация до'),
        ),
        migrations.AlterField(
            model_name='content',
            name='publish_up',
            field=models.DateTimeField(blank=True, db_index=True, help_text='<span style="color:red;">если оставить поле пустым, то с даты создания</span>', null=True, verbose_name='Публикация с'),
        ),
    ]
