# Generated by Django 4.0.1 on 2022-01-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_content_images_content_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
