# Generated by Django 4.0.1 on 2022-01-23 17:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='fulltext',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полный текст статьи'),
        ),
        migrations.AlterField(
            model_name='content',
            name='introtext',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Вступительный текст статьи'),
        ),
    ]
